site_name: Sql розробка та аналітика
use_directory_urls: true

theme:
  name: bootstrap
  custom_dir: overrides
  highlightjs: true
  add_sidebar: false
  favicon: assets/favicon.png

plugins:
  - search
  - i18n:
      languages:
        - locale: uk
          name: Українська
          site_name: Sql розробка та аналітика
          default: true
        - locale: en
          name: English 
          site_name: SQL Development and Analytics
      fallback_to_default: false
      reconfigure_nav: false

repo_name: My SQL Scripts
# repo_url: https://github.com/Nenssi/my-sql-docs

extra_css:
  - stylesheets/extra.css

nav:
  - index.md
  - about.md
  - sql_scripts.md
  - contact.md
  - '🌐 Language':
    - '🇺🇦 Українська': 'https://nenssi.github.io/my-docs/'
    - '🇺🇸 English': 'https://nenssi.github.io/my-docs/en/'